#
# docker-compose.yml
#
services:
  #
  # database by PostgreSQL
  #
  db:
    container_name: db
    hostname: ${DATABASE_HOST}
    image: postgres:17.2
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - be
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DBNAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

  #
  # Reverse Proxy
  #
  reverse-proxy:
    container_name: reverse-proxy
    hostname: ${REVERSEPROXY_HOST}
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    networks:
      - be
    volumes:
      # NGINXのコンフィグファイルをホストOSから、ゲストOSに連結する
      - ./reverse-proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      # HTTPS用の証明書とキーをホストOSから、ゲストOSに連結する
      - ./reverse-proxy/certificates/server.crt:/etc/nginx/conf.d/server.crt:Z
      - ./reverse-proxy/certificates/server.key:/etc/nginx/conf.d/server.key:Z
      # NGINXのWebアプリ（index.html等）をホストOSから、ゲストOSに連結する
      - ./reverse-proxy/html:/usr/share/nginx/html
      # log出力
      - ./reverse-proxy/logs:/var/log/nginx

networks:
  be: {}
