#
# docker-compose.yml
#
services:
  #
  # database by PostgreSQL
  #
  db:
    container_name: db
    hostname: ${DATABASE_HOST}
    image: postgres:17.4
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - ${DATABASE_PORT}:5432
    networks:
      - be
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DBNAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

networks:
  be: {}
